cmd_drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.o := /home/builder/toolchain/5.3/bin/aarch64-linux-android-gcc -Wp,-MD,drivers/gpu/arm/t7xx/r15p0/.mali_kbase_strings.o.d  -nostdinc -isystem /home/builder/toolchain/5.3/bin/../lib/gcc/aarch64-linux-android/5.4.1/include -I/home/builder/Samsung_Nougat/arch/arm64/include -Iarch/arm64/include/generated  -Iinclude -I/home/builder/Samsung_Nougat/arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I/home/builder/Samsung_Nougat/include/uapi -Iinclude/generated/uapi -include /home/builder/Samsung_Nougat/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm64/mach-exynos/include -Iarch/arm64/plat-samsung/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -Wno-logical-not-parentheses -fno-delete-null-pointer-checks -fdiagnostics-show-option -fno-pic -fno-diagnostics-show-caret -fno-pic -Wno-unused-variable -mtune=cortex-a57.cortex-a53 -std=gnu89 -DANDROID_VERSION=700000 -DANDROID_MAJOR_VERSION=7 -fno-delete-null-pointer-checks -Wno-maybe-uninitialized -Os -Wno-maybe-uninitialized -mgeneral-regs-only -fno-pic -Wframe-larger-than=2064 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -DMALI_CUSTOMER_RELEASE=1 -DMALI_KERNEL_TEST_API=0 -DMALI_UNIT_TEST=0 -DMALI_ERROR_INJECT_ON=0 -DMALI_MOCK_TEST=0 -DMALI_COVERAGE=0 -DMALI_INSTRUMENTATION_LEVEL=0 -DMALI_RELEASE_NAME=\""r15p0-00rel0"\" -DMALI_GCC_WORKAROUND_MIDCOM_4598=0 -DMALI_KBASE_THIRDPARTY_PATH=../../drivers/gpu/arm/t7xx/r15p0/platform/ -I/home/builder/Samsung_Nougat/drivers/staging/android -Idrivers/gpu/arm/t7xx/r15p0 -Idrivers/gpu/arm/t7xx/r15p0/platform_dummy -I -Idrivers/gpu/arm/t7xx/r15p0/../../../base -I/home/builder/Samsung_Nougat/include/linux -Idrivers/gpu/arm/t7xx/r15p0/backend/gpu -DMALI_CUSTOMER_RELEASE=1 -DMALI_KERNEL_TEST_API=0 -DMALI_UNIT_TEST=0 -DMALI_ERROR_INJECT_ON=0 -DMALI_MOCK_TEST=0 -DMALI_COVERAGE=0 -DMALI_INSTRUMENTATION_LEVEL=0 -DMALI_RELEASE_NAME=\""r15p0-00rel0"\" -DMALI_GCC_WORKAROUND_MIDCOM_4598=0 -DMALI_KBASE_THIRDPARTY_PATH=../../drivers/gpu/arm/t7xx/r15p0/platform/ -I/home/builder/Samsung_Nougat/drivers/staging/android -Idrivers/gpu/arm/t7xx/r15p0 -Idrivers/gpu/arm/t7xx/r15p0/platform_dummy -Idrivers/gpu/arm/t7xx/r15p0/../../../base -I/home/builder/Samsung_Nougat/include/linux -Idrivers/gpu/arm/t7xx/r15p0 -Idrivers/gpu/arm/t7xx/r15p0/platform/exynos -Idrivers/gpu/arm/t7xx/r15p0/backend/gpu    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(mali_kbase_strings)"  -D"KBUILD_MODNAME=KBUILD_STR(mali_kbase)" -c -o drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.o drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.c

source_drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.o := drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.c

deps_drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.o := \
  drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.h \

drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.o: $(deps_drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.o)

$(deps_drivers/gpu/arm/t7xx/r15p0/mali_kbase_strings.o):
